CREATE SEQUENCE ENTITY_ID_SEQ START 1;

CREATE TABLE ENTITY
(
    ENTITY_ID BIGSERIAL    NOT NULL,
    ATTRIBUTE VARCHAR(255) NOT NULL,
    VALUE     JSONB,
    TX        BIGINT       NOT NULL,
    OP        BOOLEAN      NOT NULL
);

CREATE INDEX idx_entity_id ON ENTITY (ENTITY_ID);
CREATE INDEX idx_entity_attribute ON ENTITY (ATTRIBUTE);
CREATE INDEX idx_entity_tx ON ENTITY (TX);
CREATE INDEX idx_entity_id_tx_op ON ENTITY (ENTITY_ID, TX, OP);

