CREATE SEQUENCE ENTITY_ID_SEQ START 1;

CREATE TABLE ENTITY
(
    ID   BIGSERIAL NOT NULL,
    DATA JSONB     NOT NULL
);

CREATE INDEX IDX_ENTITY_ID ON ENTITY (ID);
CREATE INDEX IDX_ENTITY_ID_DATA ON ENTITY USING GIN (DATA);
CREATE INDEX IDX_ENTITY_ID_DATA_READ ON ENTITY ((data ->> 'read'));
CREATE INDEX IDX_ENTITY_ID_DATA_IFACES ON ENTITY ((data ->> 'ifaces'));
