/*
 * This file is generated by jOOQ.
 */
package io.heapy.komok.database.keys


import io.heapy.komok.database.tables.Iface
import io.heapy.komok.database.tables.records.IfaceRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val IFACE_PKEY: UniqueKey<IfaceRecord> = Internal.createUniqueKey(Iface.IFACE, DSL.name("iface_pkey"), arrayOf(Iface.IFACE.ID), true)
