# docker-compose -f docker-compose.dev.yml up -d
name: "komok"

services:
  database:
    image: "mongo:latest"
    restart: "always"
    mem_limit: "512m"
    memswap_limit: "0m"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "komok"
      MONGO_INITDB_ROOT_PASSWORD: "komok"
    volumes:
        - "komok-mg-data:/data/db"
    ports:
      - "27017:27017"
  mongo-express:
    image: "mongo-express:latest"
    restart: "always"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://komok:komok@database:27017/"
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: "komok"
      ME_CONFIG_BASICAUTH_PASSWORD: "komok"
    depends_on:
      - "database"
volumes:
  komok-mg-data:
