enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")
rootProject.name = "komok"

include("komok-app")
include("komok-auth-common")
include("komok-dao-mg")
include("komok-server-common")
include("komok-server-cookie-auth")
include("komok-server-core")
include("komok-tech-config")
include("komok-tech-config-common")
include("komok-tech-config-dotenv")
include("komok-tech-core")
include("komok-tech-decorators-ksp")
include("komok-tech-decorators-lib")
include("komok-tech-di")
include("komok-tech-di-ez")
include("komok-tech-di-ez-ksp")
include("komok-tech-di-ez-lib")
include("komok-tech-di-ez-test")
include("komok-tech-di-lib")
include("komok-tech-di-test")
include("komok-tech-di-test-central")
include("komok-tech-di-test-next")
include("komok-tech-ktor-htmx")
include("komok-tech-logging")
include("komok-tech-time")
include("komok-tech-to-be-injected")
