enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")
rootProject.name = "komok"

include("komok-app")
include("komok-auth-common")
include("komok-dao-mg")
include("komok-server-common")
include("komok-server-cookie-auth")
include("komok-server-core")
include("komok-tech-config")
include("komok-tech-core")
include("komok-tech-di")
include("komok-tech-di-ez")
include("komok-tech-di-lib")
include("komok-tech-di-test")
include("komok-tech-di-test-central")
include("komok-tech-di-test-next")
include("komok-tech-dotenv")
include("komok-tech-logging")
include("komok-tech-to-been-injected")
