/*
 * This file is generated by jOOQ.
 */
package io.heapy.komok.database.indexes


import io.heapy.komok.database.tables.Entity
import io.heapy.komok.database.tables.Iface

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val IDX_ENTITY_ID: Index = Internal.createIndex(DSL.name("idx_entity_id"), Entity.ENTITY, arrayOf(Entity.ENTITY.ID), false)
val IDX_ENTITY_ID_DATA: Index = Internal.createIndex(DSL.name("idx_entity_id_data"), Entity.ENTITY, arrayOf(Entity.ENTITY.DATA), false)
val IDX_INTERFACE_ID: Index = Internal.createIndex(DSL.name("idx_interface_id"), Iface.IFACE, arrayOf(Iface.IFACE.ID), false)
