/*
 * This file is generated by jOOQ.
 */
package io.heapy.komok.database.indexes


import io.heapy.komok.database.tables.Entity
import io.heapy.komok.database.tables.Iface

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val IDX_ENTITY_ATTRIBUTE: Index = Internal.createIndex(DSL.name("idx_entity_attribute"), Entity.ENTITY, arrayOf(Entity.ENTITY.ATTRIBUTE), false)
val IDX_ENTITY_ID: Index = Internal.createIndex(DSL.name("idx_entity_id"), Entity.ENTITY, arrayOf(Entity.ENTITY.ENTITY_ID), false)
val IDX_ENTITY_ID_TX_OP: Index = Internal.createIndex(DSL.name("idx_entity_id_tx_op"), Entity.ENTITY, arrayOf(Entity.ENTITY.ENTITY_ID, Entity.ENTITY.TX, Entity.ENTITY.OP), false)
val IDX_ENTITY_TX: Index = Internal.createIndex(DSL.name("idx_entity_tx"), Entity.ENTITY, arrayOf(Entity.ENTITY.TX), false)
val IDX_INTERFACE_ID: Index = Internal.createIndex(DSL.name("idx_interface_id"), Iface.IFACE, arrayOf(Iface.IFACE.ID), false)
