/*
 * This file is generated by jOOQ.
 */
package io.heapy.komok.database.tables


import io.heapy.komok.database.Public
import io.heapy.komok.database.indexes.IDX_ENTITY_ID
import io.heapy.komok.database.indexes.IDX_ENTITY_ID_DATA
import io.heapy.komok.database.tables.records.EntityRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Entity(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, EntityRecord>?,
    parentPath: InverseForeignKey<out Record, EntityRecord>?,
    aliased: Table<EntityRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<EntityRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.entity</code>
         */
        val ENTITY: Entity = Entity()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<EntityRecord> = EntityRecord::class.java

    /**
     * The column <code>public.entity.id</code>.
     */
    val ID: TableField<EntityRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("nextval('entity_id_seq1'::regclass)"), SQLDataType.BIGINT)), this, "")

    /**
     * The column <code>public.entity.data</code>.
     */
    val DATA: TableField<EntityRecord, JSONB?> = createField(DSL.name("data"), SQLDataType.JSONB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<EntityRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<EntityRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<EntityRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.entity</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.entity</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.entity</code> table reference
     */
    constructor(): this(DSL.name("entity"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_ENTITY_ID, IDX_ENTITY_ID_DATA)
    override fun `as`(alias: String): Entity = Entity(DSL.name(alias), this)
    override fun `as`(alias: Name): Entity = Entity(alias, this)
    override fun `as`(alias: Table<*>): Entity = Entity(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Entity = Entity(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Entity = Entity(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Entity = Entity(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Entity = Entity(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Entity = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Entity = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Entity = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Entity = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Entity = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Entity = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Entity = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Entity = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Entity = where(DSL.notExists(select))
}
