/*
 * This file is generated by jOOQ.
 */
package io.heapy.komok.database.tables.pojos


import io.heapy.komok.database.tables.interfaces.IEntity

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Entity(
    override val id: Long? = null,
    override val `data`: JSONB
): IEntity {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Entity = other as Entity
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.`data` != o.`data`)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.`data`.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Entity (")

        sb.append(id)
        sb.append(", ").append(`data`)

        sb.append(")")
        return sb.toString()
    }
}
