/*
 * This file is generated by jOOQ.
 */
package io.heapy.komok.database.tables.pojos


import io.heapy.komok.database.tables.interfaces.IPerson


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Person(
    override val id: Long? = null,
    override val name: String,
    override val age: Int
): IPerson {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Person = other as Person
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.name != o.name)
            return false
        if (this.age != o.age)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.name.hashCode()
        result = prime * result + this.age.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Person (")

        sb.append(id)
        sb.append(", ").append(name)
        sb.append(", ").append(age)

        sb.append(")")
        return sb.toString()
    }
}
