/*
 * This file is generated by jOOQ.
 */
package io.heapy.komok.database


import io.heapy.komok.database.sequences.ENTITY_ID_SEQ
import io.heapy.komok.database.tables.Entity
import io.heapy.komok.database.tables.Iface

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Sequence
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.entity</code>.
     */
    val ENTITY: Entity get() = Entity.ENTITY

    /**
     * The table <code>public.iface</code>.
     */
    val IFACE: Iface get() = Iface.IFACE

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getSequences(): List<Sequence<*>> = listOf(
        ENTITY_ID_SEQ
    )

    override fun getTables(): List<Table<*>> = listOf(
        Entity.ENTITY,
        Iface.IFACE
    )
}
