/*
 * This file is generated by jOOQ.
 */
package io.heapy.komok.database.tables.interfaces


import java.io.Serializable

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface IEntity : Serializable {
    val id: Long?
    val `data`: JSONB
}
