/*
 * This file is generated by jOOQ.
 */
package io.heapy.komok.database.tables.interfaces


import java.io.Serializable

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface IIface : Serializable {
    val id: Long?
    val name: String
    val schema: JSONB?
}
