/*
 * This file is generated by jOOQ.
 */
package io.heapy.komok.database.tables.interfaces


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface IPerson : Serializable {
    val id: Long?
    val name: String
    val age: Int
}
