/*
 * This file is generated by jOOQ.
 */
package io.heapy.komok.database.tables.references


import io.heapy.komok.database.tables.Entity
import io.heapy.komok.database.tables.Iface



/**
 * The table <code>public.entity</code>.
 */
val ENTITY: Entity = Entity.ENTITY

/**
 * The table <code>public.iface</code>.
 */
val IFACE: Iface = Iface.IFACE
