/*
 * This file is generated by jOOQ.
 */
package io.heapy.komok.database.tables.references


import io.heapy.komok.database.tables.Person



/**
 * The table <code>public.person</code>.
 */
val PERSON: Person = Person.PERSON
